### ISSUE TITLE
Merge conflicts not handled

### ISSUE THREAD

**Issue by JensRantil** [tibdex/github-cherry-pick#9]
I am interested in solving the problem of cherry-picking using Github's low-level API, too, however in Golang programming language.

I just read [the Git Internals chapter of the Pro Git book](https://git-scm.com/book/en/v1/Git-Internals) (great!) and one thing I note is that [creating commits using the low-level "plumbing" API](https://git-scm.com/book/en/v1/Git-Internals-Git-Objects#Commit-Objects) does not work with diff/patch but with file content/trees. As such, creating commits by referring to trees using the low-level Github API is _not_ the same as doing a `git cherry-pick XXX` as it wont handle merge conflicts at all. It _is_ something close to `git cherry-pick -Xtheirs XXX` with the difference that the new commit XXX will modify the file to look exactly as it looked at commit XXX. Really what you want to do is to extract the _diff_ from XXX^ to XXX, create a new tree based on that and then create a commit.

Are you handling this? I'm by no means a TypeScript expert, but from what I understand in https://github.com/tibdex/github-cherry-pick/blob/master/src/index.ts you are not. Have you considered how to handle it? One way of doing it would be to iteratively do something (in pseudo code)

```
foreach commit in commit_list:
    newtree = commit.tree
    foreach filediff in commit.modified_files:
        # https://developer.github.com/v3/git/trees/#create-a-tree
        newtree = create_tree(from=newtree, file_content=apply_diff(commit.previous, filediff))

# https://developer.github.com/v3/git/commits/#create-a-commit
create_new_commit(from, newtree)
```

I understand it would be slower, but it's the correct way of doing it, I think.

**Comment by JensRantil** [comment]
For reference, if you're curious, I'm trying to solve https://github.com/rebbot/rebbot/issues/11 and https://github.com/rebbot/rebbot/issues/10.

**Comment by tibdex** [comment]
Hi Jens, thanks for suggesting this. However, I developed this library to make [Autorebase](https://github.com/tibdex/autorebase) possible but I now use [Autosquash](https://github.com/tibdex/autosquash) [instead](https://github.com/tibdex/autosquash/blob/9ef9ad434f3b2b41da4fed3eb77feb93ac819d01/README.md#why-squash-and-merge) so I won't spend more time trying to improve the cherry-picking.
